<?xml version ="1.0" encoding ="UTF-8"?>
<!-- ejemplodtd1.xml SUGRUPO -->
<!DOCTYPE fichero 
	[
		<!ELEMENT fichero (ficha+)>
		<!ELEMENT ficha (nombre, apellido, direccion*, DUI?)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
        <!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>		
	]>
<fichero>
	<ficha>
		<nombre sexo="femenino" edad="17">angelina</nombre>
		<apellido>Fernandez</apellido>
		<direccion>ulises, 26</direccion>
	</ficha>
</fichero>