<?xml version="1.0" encoding="UTF-8"?>
<!-- ejemplodtd1.xml SUGRUPO -->
<!DOCTYPE fichero 
[
		<!ELEMENT fichero (ficha+)>
		<!ELEMENT ficha (nombre, apellido, direccion*, DUI?, estado)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
        <!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>		
		<!ELEMENT estado (#PCDATA) >
		<!ATTLIST estado e (casado|soltero) #REQUIRED>
		]>
		
<fichero>
 <ficha>
  <nombre sexo="femenino" edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
  <estado e="soltero">soltero</estado>
 </ficha>
</fichero>
