<?xml version ="1.0" encoding ="UTF-8"?>
<!-- ejemplodtd1.xml grupo 2 -->
<!DOCTYPE fichero 
[
		<!ELEMENT fichero (ficha+, a)>
		<!ELEMENT ficha (nombre, apellido, direccion*, DUI, estado)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
		<!ATTLIST nombre tez (morena|caucacica|asiatica|latina) #REQUIRED>
        <!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>		
		<!ELEMENT estado (#PCDATA) >
		<!ATTLIST a xmlns CDATA #IMPLIED>
    	<!ATTLIST a href CDATA #IMPLIED>
    	<!ATTLIST a class CDATA #IMPLIED>
		]>
		
<fichero>
 <ficha>
  <nombre sexo="femenino" tez="asiatica" edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/fernandez, 28</direccion>
  <DUI>12345678-9</DUI>
  <estado>soltero</estado>
 </ficha>

 <a xmlns="http://www.w3.org/1999/xhtml" href="../../index.html" class="keychainify-checked">INDEX</a>

</fichero>