=== JoseMonterrosa/TareaGuia32/archivos-para-guia-32/parte-4/fichero4-4.dtd
<!â€”fichero4-4.dtd -->
<!ELEMENT equipo (fichaJugador+, a)>
<!ELEMENT fichaJugador (nombre, apellido, posicion, nacionalidad?)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
<!ATTLIST nombre edad  CDATA  #IMPLIED>
<!ATTLIST nombre estatura  CDATA  #IMPLIED>
<!ATTLIST nombre peso  CDATA  #REQUIRED>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT posicion (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ATTLIST a xmlns CDATA #IMPLIED>
<!ATTLIST a href CDATA #IMPLIED>
<!ATTLIST a class CDATA #IMPLIED>

=== JoseMonterrosa/TareaGuia32/archivos-para-guia-32/parte-4/Ejercicio-4-4.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilo4-4.css" ?>
<!DOCTYPE fichero SYSTEM "fichero4-4.dtd">
<equipo>
 <fichaJugador>
  <nombre sexo="masculino" edad="22" estatura="194" pero="85">
         virgil 
  </nombre>
  <apellido>van dijk</apellido>
  <posicion>defensa</posicion>
  <nacionalidad>neerland√©s</nacionalidad>
</fichaJugador>
 <fichaJugador>
  <nombre sexo="masculino" edad="38" estatura="174" pero="80">
         Leonel Andres 
  </nombre>
  <apellido>Messi</apellido>
  <posicion>delantero</posicion>
  <nacionalidad>argentino</nacionalidad>
</fichaJugador>
</equipo>
