=== JoseMonterrosa/TareaGuia32/archivos-para-guia-32/parte-3/equipos.dtd
<!--equipos.dtd-->
<!ELEMENT grupo (equipo+)>
<!ATTLIST grupo universidad CDATA #FIXED "Universidad de El Salvador">
<!ELEMENT equipo (facultad, carrera, materia, numclase, profesor, actividad, numgrupo, tema, coordinador, (integrante)3, subcoordinador, nomequipo?)>
<!ELEMENT facultad (nombre, codigo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT carrera (nombre, codigo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT codigo (#PCDATA)">
<!ELEMENT materia (#PCDATA)>
<!ELEMENT numclase (#PCDATA)>
<!ATTLIST numclase clase (GT|GL|GD) #REQUIRED>
<!ELEMENT profesor (#PCDATA)>
<!ELEMENT actividad (nombre, porcentaje)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT porcentaje (#PCDATA)>
<!ELEMENT numgrupo (#PCDATA)>
<!ELEMENT tema (#PCDATA)>
<!ELEMENT coordinador (carnet, nombres, apellidos)>
<!ATTLIST coordinador sexo CDATA "M">
<!ATTLIST coordinador edad CDATA #REQUIRED>
<!ATTLIST coordinador DUI CDATA #IMPLIED>
<!ELEMENT carnet (#PCDATA)>
<!ELEMENT nombres (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT integrante (carnet, nombres, apellidos)>
<!ATTLIST integrante sexo CDATA "M">
<!ELEMENT carnet (#PCDATA)>
<!ELEMENT nombres (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT subcoordinador (#PCDATA)>
<!ELEMENT nomequipo (#PCDATA)>

=== JoseMonterrosa/TareaGuia32/archivos-para-guia-32/parte-3/ejercicio3dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="ejercicio3.css"?>
<!DOCTYPE grupo SYSTEM "equipos.dtd">
<grupo>
  <equipo>
    <facultad>
      <nombre>Facultad de ingenieria y arquitectura</nombre>
      <codigo>FIA</codigo>
    </facultad>
    <carrera>
      <nombre>Ingenieria en sistemas informaticos</nombre>
      <codigo>I10515-1998</codigo>
    </carrera>
    <materia>Tecnicas de programacion para internet</materia>
    <numclase clase="Laboratorio">01</numclase>
    <profesor>Ing Balmore</profesor>
    <actividad>
      <nombre>Guia 32</nombre>
      <porcentaje>10%</porcentaje>
    </actividad>
    <numgrupo>02</numgrupo>
    <tema>XML bien estructurado</tema>
    <coordinador edad="20" sexo="M">
      <carnet>GM21007</carnet>
      <nombres>Jose David</nombres>
      <apellidos>Gonzalez Morataya</apellidos>
    </coordinador>
    <integrante sexo="M">
      <carnet>MB21009</carnet>
      <nombres>Jose Roberto</nombres>
      <apellidos>Monterrosa Bonilla</apellidos>
    </integrante>
    <subcoordinador>Tadeo</subcoordinador>
    <nomequipo>grupo02</nomequipo>
  </equipo>
</grupo>
